export const APP_NAME = 'wordy'
export const APP_DOMAIN = 'wordy.app'
export const APP_URL = 'https://wordy.app'
export const PUBLISHER_NAME = 'brnysn'
export const PUBLISHER_DOMAIN = 'brnysn.com'
export const PUBLISHER_URL = 'https://brnysn.com'
export const WEB_CDN = 'https://brnysn.com/wordy'
export const ALPHABET_LENGTH = 26
export const ANSWER_CHAR_LENGTH = 64
export const GAME_TIME_LIMIT = 5 * 60 * 1000 // 5min
export const UNSUPPORTED_HEIGHT = 520
